// THE CARROT - enclosure version badge, revision r1 (2026-09)
//
// GENERATED by hardware/enclosure/tools/gen_enclosure_badge.py - edit the
// generator (or hardware/kicad/tools/boarddef.py), not this file.
//
// The scheme is "The Tally". Three marks, meant for the underside or the rear
// wall of the printed case:
//   * a Morse strip spelling this tier's nickname, which reads as decorative
//     ribbing until somebody notices the rhythm is irregular;
//   * a revision tally - 1 stroke(s) = r1 - raised so it can be
//     counted by thumb without reading anything;
//   * the carrot-and-stick mascot, one stage further along for each tier up
//     the range: stick / stick + string / stick + string + carrot.
//
// Usage in your own case:
//   union()     { my_case(); badge(mode="emboss"); }   // raised marks
//   difference(){ my_case(); badge(mode="engrave"); }  // recessed marks
// Position it yourself with translate()/rotate(); the badge is drawn in the
// XY plane growing in +Z, origin at its lower-left corner.

tier      = "12key";
nickname  = "THE CARROT";
revision  = 1;
build_tag = "2026-09";

tile_w = 70.0;
tile_h = 36.0;
tile_t = 2.0;
relief = 0.80;   // raised height, or cut depth when engraving
text_marks = true;       // set false if your slicer/printer hates fine text

module marks() {
  linear_extrude(height = relief * 2)   // 2x so an engrave cut passes through
    polygon(points = [[5.000, 8.550], [7.700, 8.550], [7.700, 9.450], [5.000, 9.450]]);
    polygon(points = [[8.600, 8.550], [9.500, 8.550], [9.500, 9.450], [8.600, 9.450]]);
    polygon(points = [[10.400, 8.550], [13.100, 8.550], [13.100, 9.450], [10.400, 9.450]]);
    polygon(points = [[14.000, 8.550], [14.900, 8.550], [14.900, 9.450], [14.000, 9.450]]);
    polygon(points = [[17.600, 8.550], [18.500, 8.550], [18.500, 9.450], [17.600, 9.450]]);
    polygon(points = [[19.400, 8.550], [22.100, 8.550], [22.100, 9.450], [19.400, 9.450]]);
    polygon(points = [[24.800, 8.550], [25.700, 8.550], [25.700, 9.450], [24.800, 9.450]]);
    polygon(points = [[26.600, 8.550], [29.300, 8.550], [29.300, 9.450], [26.600, 9.450]]);
    polygon(points = [[30.200, 8.550], [31.100, 8.550], [31.100, 9.450], [30.200, 9.450]]);
    polygon(points = [[33.800, 8.550], [34.700, 8.550], [34.700, 9.450], [33.800, 9.450]]);
    polygon(points = [[35.600, 8.550], [38.300, 8.550], [38.300, 9.450], [35.600, 9.450]]);
    polygon(points = [[39.200, 8.550], [40.100, 8.550], [40.100, 9.450], [39.200, 9.450]]);
    polygon(points = [[42.800, 8.550], [45.500, 8.550], [45.500, 9.450], [42.800, 9.450]]);
    polygon(points = [[46.400, 8.550], [49.100, 8.550], [49.100, 9.450], [46.400, 9.450]]);
    polygon(points = [[50.000, 8.550], [52.700, 8.550], [52.700, 9.450], [50.000, 9.450]]);
    polygon(points = [[55.400, 8.550], [58.100, 8.550], [58.100, 9.450], [55.400, 9.450]]);
    polygon(points = [[5.500, 14.000], [4.500, 14.000], [4.500, 10.000], [5.500, 10.000]]);
    polygon(points = [[44.000, 28.420], [45.045, 28.087], [55.875, 20.440], [55.020, 19.680]]);
    polygon(points = [[46.090, 27.185], [46.850, 26.947], [47.705, 26.045], [46.945, 25.760]]);
    polygon(points = [[55.875, 20.440], [56.255, 20.630], [57.870, 17.020], [59.105, 13.980], [58.535, 13.790], [57.205, 16.830]]);
    polygon(points = [[57.490, 13.220], [60.530, 12.840], [59.580, 6.000], [58.440, 6.190]]);
    polygon(points = [[57.870, 13.315], [58.630, 15.500], [59.295, 15.405], [58.820, 13.315]]);
    polygon(points = [[58.915, 13.315], [60.340, 15.120], [60.910, 14.740], [59.770, 13.220]]);
    polygon(points = [[59.865, 13.125], [61.955, 13.980], [62.240, 13.410], [60.530, 12.840]]);
  if (text_marks) {
    linear_extrude(height = relief * 2)
      translate([5.0, 24.0]) text(nickname, size = 4.2, font = "Helvetica:style=Bold");
    linear_extrude(height = relief * 2)
      translate([5.0, 20.4]) text(str("~ ", tier, "  r", revision, "  ", build_tag, " ~"), size = 2.6);
  }
}

// mode = "emboss" -> raised marks sitting on the XY plane
// mode = "engrave" -> marks to subtract, sunk `relief` into the surface
module badge(mode = "emboss") {
  if (mode == "emboss") translate([0, 0, 0]) marks_clipped();
  else translate([0, 0, -relief]) marks();
}

module marks_clipped() {
  intersection() {
    marks();
    translate([-1, -1, 0]) cube([tile_w + 2, tile_h + 2, relief]);
  }
}

// Standalone tile, matching <tier>_badge.stl. Print this on its own to check
// the marks read at your layer height before committing to a whole case.
module badge_tile() {
  union() {
    cube([tile_w, tile_h, tile_t]);
    translate([0, 0, tile_t]) marks_clipped();
  }
}

badge_tile();
