"""Push-to-talk key injection: `hold(key)` / `release(key)` semantics, not
`post_key(down)`.

A single synthetic keyDown+keyUp never autorepeats — autorepeat is
generated by the HID layer for physical keys only — so Claude Code's
hold-to-talk (which infers "still held" from the OS autorepeat byte
stream, and "released" from the repeats stopping) sees a whole hold as one
tap. `RepeatingKeyInjector` owns the "hold" by reposting keyDown itself at
the OS's configured repeat cadence for as long as the key should be down.

Confirmed empirically (2026-09-14, host/experiments/ptt_autorepeat_check.py
against a live Claude Code session): a single keyDown/keyUp never
registers as a hold; a repeated plain keyDown at ~33ms cadence does,
whether or not the low-level `kCGKeyboardEventAutorepeat` flag is set on
the repeats. So the fix only needs cadence, not the flag — Claude Code
(and presumably any terminal-hosted app in the same boat) infers "held"
from the repeated bytes reaching it, not from anything at the CGEvent
level a terminal can't see anyway.
"""

from __future__ import annotations

import subprocess
import threading
from typing import Callable, Protocol

# Fallback cadence if reading the user's keyboard settings fails: macOS's
# own defaults (250ms initial delay, then a key every ~33ms).
DEFAULT_INITIAL_DELAY_S = 0.25
DEFAULT_REPEAT_INTERVAL_S = 0.033

# Auto-release ceiling: a lost voice.hold.stop (e.g. the board is unplugged
# mid-hold) must never leave a key stuck down indefinitely.
DEFAULT_MAX_HOLD_S = 120.0


class KeyInjector(Protocol):
    def hold(self, pid: int, keycode: int) -> None: ...

    def release(self, pid: int, keycode: int) -> None: ...


def macos_key_repeat_timing() -> tuple[float, float]:
    """(initial_delay_seconds, repeat_interval_seconds) read from the
    user's keyboard settings (System Settings -> Keyboard), so a held key
    looks exactly as it would if it were physical. `InitialKeyRepeat` and
    `KeyRepeat` are both in units of 1/60s. Falls back to macOS's own
    defaults if either read fails (fresh account with no override, or
    running somewhere `defaults` doesn't apply)."""

    def _read(key: str) -> int | None:
        result = subprocess.run(
            ["defaults", "read", "-g", key], check=False, capture_output=True, text=True
        )
        text = result.stdout.strip()
        return int(text) if text.lstrip("-").isdigit() else None

    initial = _read("InitialKeyRepeat")
    repeat = _read("KeyRepeat")
    initial_s = initial / 60.0 if initial is not None else DEFAULT_INITIAL_DELAY_S
    repeat_s = repeat / 60.0 if repeat is not None else DEFAULT_REPEAT_INTERVAL_S
    return initial_s, repeat_s


class RepeatingKeyInjector:
    """Delegates the actual event post to whatever the caller already uses
    to post one (e.g. `TerminalDriver.post_key`) — this class only owns
    the repeat timing and the watchdog, not the OS-specific event API."""

    def __init__(
        self,
        post_key: Callable[[int, int, bool], None],
        *,
        initial_delay: float = DEFAULT_INITIAL_DELAY_S,
        repeat_interval: float = DEFAULT_REPEAT_INTERVAL_S,
        max_hold: float = DEFAULT_MAX_HOLD_S,
        log: Callable[[str], None] = print,
    ) -> None:
        self._post_key = post_key
        self._initial_delay = initial_delay
        self._repeat_interval = repeat_interval
        self._max_hold = max_hold
        self._log = log
        self._lock = threading.Lock()
        self._thread: threading.Thread | None = None
        self._stop = threading.Event()

    def hold(self, pid: int, keycode: int) -> None:
        with self._lock:
            if self._thread is not None:
                return  # already holding; a second hold() before release() is a no-op
            self._stop.clear()
            self._post_key(pid, keycode, True)
            self._thread = threading.Thread(target=self._repeat, args=(pid, keycode), daemon=True)
            self._thread.start()

    def release(self, pid: int, keycode: int) -> None:
        with self._lock:
            if self._thread is None:
                return  # hold-stop without a matching hold-start: no-op
            self._stop.set()
            thread = self._thread
            self._thread = None
        thread.join(timeout=1.0)
        self._post_key(pid, keycode, False)

    def _repeat(self, pid: int, keycode: int) -> None:
        elapsed = 0.0
        if self._stop.wait(self._initial_delay):
            return
        elapsed += self._initial_delay
        while elapsed < self._max_hold:
            if self._stop.wait(self._repeat_interval):
                return
            elapsed += self._repeat_interval
            self._post_key(pid, keycode, True)
        self._log(f"KeyInjector: auto-released keycode {keycode} after {self._max_hold}s (watchdog)")
        with self._lock:
            if self._thread is None:
                return  # release() already ran concurrently with the watchdog firing
            self._thread = None
        self._post_key(pid, keycode, False)


class FakeKeyInjector:
    """Records calls; no timing, no threads — for Bridge-level tests where
    the injection itself isn't what's under test."""

    def __init__(self) -> None:
        self.held: list[tuple[int, int]] = []
        self.released: list[tuple[int, int]] = []

    def hold(self, pid: int, keycode: int) -> None:
        self.held.append((pid, keycode))

    def release(self, pid: int, keycode: int) -> None:
        self.released.append((pid, keycode))
